// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package order

import (
	"context"
)

// iteratorForAddOrderStock implements pgx.CopyFromSource.
type iteratorForAddOrderStock struct {
	rows                 []AddOrderStockParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddOrderStock) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddOrderStock) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].SkuID,
		r.rows[0].Count,
	}, nil
}

func (r iteratorForAddOrderStock) Err() error {
	return nil
}

func (q *Queries) AddOrderStock(ctx context.Context, arg []AddOrderStockParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_stock"}, []string{"order_id", "sku_id", "count"}, &iteratorForAddOrderStock{rows: arg})
}
